### PR TITLE
Remove drawbot.py and references, keep a stub for someday

### PR DESCRIPTION
**Pull request by rlafuente**
Looking at the profiling results, I noticed that the drawbot.py import was taking a small slice of run time.

This reminded me that the Drawbot code is just a duplicate of nodebox.py with function names changed, and is pretty outdated.

At some point we could consider a saner approach to support drawbot, such as a drawbot mixin with aliases like `fontSize = self.fontsize`. But for now the drawbot module is just eating a bit of processing time, and code is old, so cleanup is maybe appropriate.

### CODE REVIEW

**Comment by stuaxo** [comment]
This sounds good, maybe we can flatten the class hierarchy here too (or at least look again).

I think better than "might need it some day" is to remove stuff entirely were not using - more YAGNI - if we do need it in future there's always the repo and older versions for reference.

**Comment by rlafuente** [comment]
well put, next time we'll do it better :metal: removed the remaining bits and the --grammar CLI option, which is pointless atm

**Comment by stuaxo** [comment]
1_wT14bv4NEbNAvDLfTAy9ng

**Comment by stuaxo** [comment]
Are the docs for commandline updated to remove the grammar refs too ?

**Comment by stuaxo** [comment]
Maybe I can come up with a test to check the documented options match the real options.

**Pull request merged**
