### PR TITLE
Code runs too many times.

### PR DESCRIPTION
**Pull request by stuaxo**
Fix for https://github.com/shoebot/shoebot/issues/247

When `run_forever` is set

Code:
 - [x] Run once for non dynamic bots
 - [x] Run animation forever

Implement tests:
 - [ ] Run once for non dynamic bots
 - [ ] Run animation forever

Bots to test
 - [x] Animated bots
 - [x] Non animated bots
 - [x] non-animated bots re-run on Variable update

TODO for merge:
- [x] Re-add livecoding
- [x] Re-add saving images
- [x] Re-add support for "verbose" (our exception handler)
- [x] Further debug on pause / play.

### CODE REVIEW

**Comment by stuaxo** [comment]
run_forever could have a better name, currently it means "don't quit the GUI".

**Comment by stuaxo** [comment]
Current code works correctly, for non-dynamic bots... but seemingly only because _dynamic is True by default.

Tests are needed, then the logic can be corrected.

**Comment by rlafuente** [comment]
just to keep track of things: there is still an issue where the script window only renders a 200x200 square, even if size() is larger:

Screenshot_2021-04-14_22-26-57

(we discussed this problem on the chat but i think it wasn't registered anywhere)

**Comment by stuaxo** [comment]
The branch seems to fix the bug, but it doesn't run code in non-dynamic bots after shoebot Variables are changed, so that needs fixing.

**Comment by stuaxo** [comment]
The main loop very probably needs to be refactored to be more like Nodeboxes Runner class, it's really difficult to make things work properly as-is.

**Comment by stuaxo** [comment]
Test bots:

test1.bot
```python
# Non animated bot, should run once.
size(1920, 1080)

print("global scope, FRAME:", FRAME)

translate(10, 10)
rotate(FRAME)
fill(.7, .1, .1)
rect(-40, -40, 80, 80)
var("hello", TEXT, "woo")
text(hello, 20, 20)
```

test2.bot
```python
# animated bot, slow framerate
size(1920 // 4, 1080 // 4)

print("global scope, FRAME: ", FRAME)

speed(1)

def setup():
    print("setup", FRAME)
    pass

def draw():
    translate(10, 10)
    print("draw FRAME:", FRAME)
    rotate(FRAME)
    fill(.7, .1, .1)
    rect(-40, -40, 80, 80)
    var("hello", TEXT, "woo")
    text(hello, 20, 20)
    reset()
    text(f"FRAME: {FRAME}", 0, 80)
````

test3.bot

```python
# animated bot, variable framerate
size(1920 // 4, 1080 // 4)

print("global scope, FRAME:", FRAME)

speed(2)


def setup():
    var("fps", NUMBER, speed(), -30, 30)
    var("hello", TEXT, "woo")


def draw():
    translate(10, 10)
    # print("draw", FRAME)
    rotate(FRAME)
    fill(0.7, 0.1, 0.1)
    rect(-40, -40, 80, 80)
    text(hello, 20, 20)
    reset()
    text(f"FRAME: {FRAME}", 0, 80)
    speed(fps)
```

**Comment by stuaxo** [comment]
In the end this is not a total fix... non animated bots are re-run when the window is resized, and that currently means they always run at least twice.

There are a lot of fixes in here around the main loop, (running the bot and processing events is properly separated out).
- The black screen problem is fixed.
- Partial renders have a hack: the bot runs again.
- Properly fixing this will involve some rework with the graphics backend to let it redraw stuff (currently bots are drawn once to a bitmap, which is OK, except for when the bitmap is too small).
- For livecoding: Meta had to be removed since the dependency is not being supported, as a side effect the livecoding support has somewhat regressed (there are more circumstances where the whole bot is re-run).
- Getting this far was only possible due to our unit testings and integration tests that run all the examples.

**Pull request merged**
