### PR TITLE
Fix unstroked shapes being rendered as bitmaps

### PR DESCRIPTION
**Pull request by rlafuente**
Unstroked shapes are rendered as bitmaps, this is a first stab at a fix

The problem is that BezierPath._render doesn't detect fills and strokes with zero alpha values (they're Color objects so evaluate as True)

### CODE REVIEW

**Comment by rlafuente** [comment]
So the test failures demonstrated a couple of interesting improvements, pasting my log of this from the matrix chat:

ok this fix made a few more tests fail, looking at their output now
wow there seem to be some interesting aliasing differences that this fix uncovered
and on the shortest_path test example, some text now appears that was not in the expected output!

Screenshot_2021-03-19_00-27-14

left is the one after the stroke fix, right is the expected output from the tests
yep, the graph library is using nostroke() on the label, so now it appears! I never explored this lib so I didn't know that text was supposed to appear. A hidden bug found and squished!
and look at this

Screenshot_2021-03-19_00-27-16

this is the rendering (3x scale) of primitives.bot, top is the new version with the stroke fix, bottom is the current Shoebot behavior
note the edges of the square and arrows, star is also more defined now

**Comment by rlafuente** [comment]
so Stu's pointer to set the SVG version fixed the final bitmap bug, yeah <3

i also removed the code to set the fill on top of the transparent strokes, because that's not how SVG renders paths -- this is the output of Alexandre's script, with an alpha-stroked path added in inkscape (red rect):

Screenshot_2021-03-24_23-38-01

i think we should stick to the way SVG renders things (least surprise), and if someone loves their fill on top of the stroke, that can be done in the shoebot script itself? Let me know if i'm being too bold here.

**Comment by stuaxo** [comment]
I need to think on this... I don't think seeing the fill through the stroke is correct at all...
Maybe it's me, but the behaviour of fill / stroke for SVG seems completely unintuitive,
I don't know if it's Cairo or SVG itself that's at fault (or me).

If I am in a graphics program, I would think of fill and stroke, as two seperate things,
the fill is in the middle of the area up to where the stroke is, then there is the stroke and
then the outside.

Cairo, says the fill is up to the edge, the stroke is from the edge to the inside, where distance strokewidth / 2.0, and towards the outside with strokewidth / 2.0

This works fine until the stroke has alpha, and then you see the fill underneath the stroke.

Example SVG with alpha stroke.
https://www.svgshare.com/i/VPP.svg

I just don't see how you would expect that, as a user you set a stroke colour and fill colour, it seems like an implementation detail that a 3rd colour is generated where the fill "pokes through" the stroke ?

Maybe I need to find someone who understands the SVG spec to answer this, but it just doesn't seem user-friendly.

**Comment by rlafuente** [comment]
as we discussed on the matrix channel, it's best for now to stick to the spec and later we can review?

I think we're only missing the new "expected" test outputs so that it matches the new rendering, right?

**Comment by rlafuente** [comment]
updated the expected outputs and all tests pass now!

**Review by stuaxo — APPROVED** [review]

**Pull request merged**
