### PR TITLE
Added Windows msys2 Install, + minor tweaks

### PR DESCRIPTION
**Pull request by speters33w**

### CODE REVIEW

**Review by stuaxo — APPROVED** [review]
OK, looks good to me - though it might be worth removing Pillow.. I know this is needed by Windows, but the setup.py already tries to install it, it's just down to a problem in MingW that it doesn't work*

*(because GCC isn't in the PATH by default).

**Comment by stuaxo** [comment]
Thanks, merged :)

**Comment by speters33w** [comment]
I put pillow in there because the section on dependencies was specifically
for untested OS that can't use the installdependencies.sh script, and we
had so much trouble with it.
I don't care if you leave it in or take it out. It makes no difference to
me.

**Comment by stuaxo** [comment]
I removed Pillow as it's kind of a MSys specific thing - because GCC isn't in the path by default

If someone adds BSD or some other OS there will be problems, but probably different ones.

**Pull request merged**
