### PR TITLE
Documentation rework

### PR DESCRIPTION
**Pull request by rlafuente**
This is my ongoing effort to make the docs more useful and accurate. There are many significant edits and rewording, and an attempt to unify the writing style and syntax. 

Most importantly, I've removed the arg lists from the Command Reference page so that it reads more human and less technical, and moved them to docstrings in the code that are now autodocumented in the new API Reference page.

Examples are now single pages, I'd like to find out a way to have a thumbnail index for easier skimming.

There's also a couple of actual code fixes, simple enough not to warrant a separate PR (removing old unused vars, adding return statements where there weren't any)

(and many more details, I'll wrap this up in the end)

### CODE REVIEW

**Comment by rlafuente** [comment]
oh i'm actually done here now

**Comment by stuaxo** [comment]
If we merged https://github.com/shoebot/shoebot/pull/379 first then rebased this on top, will it break a lot of stuff ?

**Comment by rlafuente** [comment]
I don't see why it should be a problem, let's find out :^)

**Comment by stuaxo** [comment]
Ok, I'll merge the other one.   BTW our tests on master are still failing :(

**Review by stuaxo — APPROVED** [review]

**Pull request merged**
