### PR TITLE
Finish implementing arcs

### PR DESCRIPTION
**Pull request by rlafuente**
We're currently missing a way to measure arcs so that we can update `BezierPath.point()`

### CODE REVIEW

**Comment by rlafuente** [comment]
I just realised today that arc() is now implemented as a path element, when it should be a primitive like rect(). We should fix this

**Comment by stuaxo** [comment]
Is this because an ARC can be closed ?

**Comment by rlafuente** [comment]
ok so i've read up a bit, and seen cairo examples where arcs are part of paths, but can't for the life of me remember the link.

anyway i like how Plotdevice handles the difference between arc as primitive (which is `arc()`), and arc as path element (which is `arcto()`)

so maybe the way out would be to rename this one arcto() and make another arc() primitive?

**Comment by stuaxo** [comment]
This one
https://pycairo.readthedocs.io/en/latest/tutorial.html

**Comment by rlafuente** [comment]
ah btw this was the tutorial where arc elements are used: https://www.cairographics.org/tutorial/

**Comment by rlafuente** [comment]
i guess the new pie arc type was proper procrastination -- I still didn't work on the original purpose of this PR, which is measuring arcs :-)

**Comment by rlafuente** [comment]
ok i made up for it with some actual work on the contours() stuff for arcs. Tomorrow I'll make some example sketches to test if these are working properly

(i also found an unused `pathmode` property in paths, grobs and images, just took it out)

**Comment by rlafuente** [comment]
Going back to the original reason for this PR (have BezierPath.point() work with arcs)

It seems to me that `BezierPath.point()` is broken; I made an issue to discuss this #373

(I've implemented the arc point calculation logic in one of these commits, but BezierPath.point() needs fixing before this works)

So for the sake of all the other arc work gone into this, I think it'd be best to rename this PR to be about arcs and merge it?

**Comment by stuaxo** [comment]
Go for it.

**Pull request merged**
